version: "3"

services:
  valheim_box64:
    image: ghcr.io/gornius/valheim_box64
    environment:
      - VALHEIM_SERVER_NAME=ValheimARM64
      - VALHEIM_WORLD_NAME=ValheimARM64
      - VALHEIM_PASSWORD=VARM64PASS
      - VALHEIM_ISPUBLIC=0
      - VALHEIM_PORT=2456
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
    volumes:
      - "./server_files/:/root/server_files"
    restart: unless-stopped
